import { getEncoding } from 'js-tiktoken';
import type { JournalDocument } from '../documents/document-types.js';

const DEFAULT_MAX_TOKENS = 300;

// Embeddings are generated by Qwen3-Embedding-0.6B (see
// src/embeddings/embedding_service.py), which has its own tokenizer, not
// OpenAI's cl100k_base. No JS package ships Qwen3's exact tokenizer without
// adding a new runtime dependency (e.g. transformers.js), so cl100k_base is
// used here as an approximation for counting/splitting purposes only.
//
// Measured via src/embeddings/measure_tokenizer_divergence.py against
// journal-style sample text (see evaluation/embeddings/dataset.json):
// Qwen3 tokenizes the same text into up to ~12.5% more tokens than
// cl100k_base (worst-case ratio 1.125). QWEN_SAFETY_MARGIN reduces the
// effective split budget so a chunk that measures at maxTokens under
// cl100k_base still stays under maxTokens real Qwen3 tokens. See #136.
//
// This margin is empirical, not a hard guarantee: it's derived from one
// run over a limited sample and doesn't cover every possible input (e.g.
// unusual scripts or dense numeric/code content could diverge further).
// SentenceTransformer.encode() in embedding_service.py truncates silently
// to the model's max sequence length rather than erroring on overflow, so
// a rare miss here degrades to truncation, not a crash. Re-run the
// measurement script and re-derive this constant if MODEL_NAME or its
// pinned revision changes.
export const QWEN_SAFETY_MARGIN = 0.85;

const encoding = getEncoding('cl100k_base');

export function countTokens(text: string): number {
  return encoding.encode(text).length;
}

function splitIntoParagraphs(text: string): string[] {
  return text
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);
}

function splitIntoSentences(text: string): string[] {
  return (
    text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map((sentence) => sentence.trim()) ??
    []
  );
}

// Splits on Unicode code-point boundaries and measures each candidate with
// countTokens, rather than slicing raw BPE token ids: cl100k_base tokens are
// byte sequences, not character-aligned, so decoding an arbitrary token slice
// can land mid-character and silently emit replacement characters.
function splitOversizedWord(word: string, maxTokens: number): string[] {
  const chars = Array.from(word);
  const pieces: string[] = [];
  let start = 0;

  while (start < chars.length) {
    const remaining = chars.length - start;

    // Exponentially grow the candidate length to bound the search window
    // near the true boundary first, rather than binary-searching the full
    // remaining word on every piece — that re-tokenizes long suffixes and
    // scales quadratically for large whitespace-free inputs.
    let fit = 1;
    let probe = 2;

    while (
      probe <= remaining &&
      countTokens(chars.slice(start, start + probe).join('')) <= maxTokens
    ) {
      fit = probe;
      probe *= 2;
    }

    let lo = fit;
    let hi = Math.min(probe, remaining);

    while (lo < hi) {
      const mid = lo + Math.ceil((hi - lo) / 2);
      if (countTokens(chars.slice(start, start + mid).join('')) <= maxTokens) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }

    const pieceLength = Math.max(lo, 1);
    pieces.push(chars.slice(start, start + pieceLength).join(''));
    start += pieceLength;
  }

  return pieces;
}

function addChunk(
  chunks: JournalDocument[],
  document: JournalDocument,
  content: string,
): void {
  if (!content.trim()) {
    return;
  }

  chunks.push({
    ...document,
    content: content.trim(),
  });
}

export function chunkDocument(
  document: JournalDocument,
  maxTokens: number = DEFAULT_MAX_TOKENS,
): JournalDocument[] {
  if (!(maxTokens >= 1)) {
    throw new Error(`maxTokens must be at least 1, received ${maxTokens}`);
  }

  if (!document.content.trim()) {
    return [];
  }

  // Split against a reduced budget (see QWEN_SAFETY_MARGIN) so a chunk that
  // measures at maxTokens under cl100k_base still stays under maxTokens real
  // Qwen3 tokens.
  const effectiveMaxTokens = Math.max(
    1,
    Math.floor(maxTokens * QWEN_SAFETY_MARGIN),
  );

  // Keep small journal records intact.
  if (countTokens(document.content) <= effectiveMaxTokens) {
    return [document];
  }

  const paragraphs = splitIntoParagraphs(document.content);

  const chunks: JournalDocument[] = [];
  let currentChunk = '';

  for (const paragraph of paragraphs) {
    const paragraphCandidate = currentChunk
      ? `${currentChunk}\n\n${paragraph}`
      : paragraph;

    // The paragraph fits in the current chunk.
    if (countTokens(paragraphCandidate) <= effectiveMaxTokens) {
      currentChunk = paragraphCandidate;
      continue;
    }

    // Save the current chunk before processing the large paragraph.
    if (currentChunk) {
      addChunk(chunks, document, currentChunk);
      currentChunk = '';
    }

    // The paragraph itself fits in one chunk.
    if (countTokens(paragraph) <= effectiveMaxTokens) {
      currentChunk = paragraph;
      continue;
    }

    // The paragraph is too large, so split it into sentences.
    const sentences = splitIntoSentences(paragraph);

    for (const sentence of sentences) {
      const sentenceCandidate = currentChunk
        ? `${currentChunk} ${sentence}`
        : sentence;

      if (countTokens(sentenceCandidate) <= effectiveMaxTokens) {
        currentChunk = sentenceCandidate;
        continue;
      }

      // Sentence candidate doesn't fit.
      if (currentChunk) {
        addChunk(chunks, document, currentChunk);
        currentChunk = '';
      }

      // Now we're starting with the sentence alone.
      if (countTokens(sentence) <= effectiveMaxTokens) {
        currentChunk = sentence;
        continue;
      }

      // The sentence itself is too large.
      const words = sentence.split(/\s+/);
      let sentenceChunk = '';

      for (const word of words) {
        const candidate = sentenceChunk ? `${sentenceChunk} ${word}` : word;

        if (countTokens(candidate) <= effectiveMaxTokens) {
          sentenceChunk = candidate;
        } else if (countTokens(word) > effectiveMaxTokens) {
          if (sentenceChunk) {
            addChunk(chunks, document, sentenceChunk);
          }

          const pieces = splitOversizedWord(word, effectiveMaxTokens);
          for (const piece of pieces.slice(0, -1)) {
            addChunk(chunks, document, piece);
          }

          sentenceChunk = pieces[pieces.length - 1] ?? '';
        } else {
          if (sentenceChunk) {
            addChunk(chunks, document, sentenceChunk);
          }

          sentenceChunk = word;
        }
      }

      if (sentenceChunk) {
        currentChunk = sentenceChunk;
      }
    }
  }

  // Save the final chunk.
  if (currentChunk) {
    addChunk(chunks, document, currentChunk);
  }

  return chunks;
}

export function chunkDocuments(
  documents: JournalDocument[],
  maxTokens: number = DEFAULT_MAX_TOKENS,
): JournalDocument[] {
  return documents.flatMap((document) => chunkDocument(document, maxTokens));
}
