import { getEncoding } from 'js-tiktoken';
import type {
  DocumentSourceType,
  JournalDocument,
} from '../documents/document-types.js';

const DEFAULT_MAX_TOKENS = 300;
const DEFAULT_OVERLAP_TOKENS = 50;

// Per-sourceType overrides for chunking budgets. Every entry currently
// matches the flat defaults above, so behavior is unchanged until a caller
// (or a future tuning pass backed by eval data) opts a specific sourceType
// into a different maxTokens/overlapTokens. `overlapTokens` is optional per
// entry — when omitted, chunkDocument falls back to its own scaled default.
export const SOURCE_TYPE_CHUNK_CONFIG: Readonly<
  Record<DocumentSourceType, Readonly<{ maxTokens: number; overlapTokens?: number }>>
> = {
  injury: { maxTokens: DEFAULT_MAX_TOKENS },
  symptom: { maxTokens: DEFAULT_MAX_TOKENS },
  treatment: { maxTokens: DEFAULT_MAX_TOKENS },
  medical_visit: { maxTokens: DEFAULT_MAX_TOKENS },
  timeline_event: { maxTokens: DEFAULT_MAX_TOKENS },
};

// Embeddings are generated by Qwen3-Embedding-0.6B (see
// src/embeddings/embedding_service.py), which has its own tokenizer, not
// OpenAI's cl100k_base. No JS package ships Qwen3's exact tokenizer without
// adding a new runtime dependency (e.g. transformers.js), so cl100k_base is
// used here as an approximation for counting/splitting purposes only.
//
// Measured via src/embeddings/measure_tokenizer_divergence.py against
// journal-style sample text (see evaluation/embeddings/dataset.json), with
// add_special_tokens=True to match SentenceTransformer.encode()'s
// production default: Qwen3 tokenizes the same text into up to ~16.7% more
// tokens than cl100k_base (worst-case ratio 1.167). QWEN_SAFETY_MARGIN
// reduces the effective split budget so a chunk that measures at maxTokens
// under cl100k_base still stays under maxTokens real Qwen3 tokens. See #136.
//
// The break-even margin is 1/1.167 ≈ 0.857; 0.82 adds ~5% headroom on top
// of that to tolerate sample-to-sample variance beyond the measured worst
// case.
//
// This margin is empirical, not a hard guarantee: it's derived from one
// run over a limited sample and doesn't cover every possible input (e.g.
// unusual scripts or dense numeric/code content could diverge further).
// SentenceTransformer.encode() in embedding_service.py truncates silently
// to the model's max sequence length rather than erroring on overflow, so
// a rare miss here degrades to truncation, not a crash. Re-run the
// measurement script and re-derive this constant if MODEL_NAME or its
// pinned revision changes.
export const QWEN_SAFETY_MARGIN = 0.82;

const encoding = getEncoding('cl100k_base');

export function countTokens(text: string): number {
  return encoding.encode(text).length;
}

function splitIntoParagraphs(text: string): string[] {
  return text
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);
}

// Splits on the labeled-field boundaries the document builders already
// produce (`document-builder.ts` joins sentences like "Notes: ... Cause:
// ..." with no blank lines between them, so splitIntoParagraphs never finds
// a boundary inside a single record). A field boundary is a sentence-ending
// period followed by a capitalized "Label:" — e.g. "... improvement.
// Notes: patient reports increased pain." Sits between paragraph- and
// sentence-splitting in the fit cascade.
function splitIntoFields(text: string): string[] {
  return text
    .split(/(?<=\.)\s+(?=[A-Z][A-Za-z ]{2,30}:)/)
    .map((field) => field.trim())
    .filter(Boolean);
}

function splitIntoSentences(text: string): string[] {
  return (
    text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map((sentence) => sentence.trim()) ??
    []
  );
}

// Splits on Unicode code-point boundaries and measures each candidate with
// countTokens, rather than slicing raw BPE token ids: cl100k_base tokens are
// byte sequences, not character-aligned, so decoding an arbitrary token slice
// can land mid-character and silently emit replacement characters.
function splitOversizedWord(
  word: string,
  maxTokens: number,
  overlapTokens = 0,
): string[] {
  const chars = Array.from(word);
  const pieces: string[] = [];
  let start = 0;

  while (start < chars.length) {
    const remaining = chars.length - start;

    // Exponentially grow the candidate length to bound the search window
    // near the true boundary first, rather than binary-searching the full
    // remaining word on every piece — that re-tokenizes long suffixes and
    // scales quadratically for large whitespace-free inputs.
    let fit = 1;
    let probe = 2;

    while (
      probe <= remaining &&
      countTokens(chars.slice(start, start + probe).join('')) <= maxTokens
    ) {
      fit = probe;
      probe *= 2;
    }

    let lo = fit;
    let hi = Math.min(probe, remaining);

    while (lo < hi) {
      const mid = lo + Math.ceil((hi - lo) / 2);
      if (countTokens(chars.slice(start, start + mid).join('')) <= maxTokens) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }

    const pieceLength = Math.max(lo, 1);
    const pieceEnd = start + pieceLength;
    pieces.push(chars.slice(start, pieceEnd).join(''));

    if (pieceEnd >= chars.length || overlapTokens <= 0) {
      start = pieceEnd;
      continue;
    }

    // Back the next piece's start up by a token-budgeted trailing slice of
    // this piece, so consecutive pieces honor the same overlap contract as
    // every other chunk boundary. Capped below pieceLength (not just by
    // overlapTokens < maxTokens) to guarantee forward progress regardless of
    // any tokenizer non-monotonicity.
    let overlapFit = 0;
    let overlapProbe = 1;

    while (
      overlapProbe < pieceLength &&
      countTokens(chars.slice(pieceEnd - overlapProbe, pieceEnd).join('')) <=
        overlapTokens
    ) {
      overlapFit = overlapProbe;
      overlapProbe *= 2;
    }

    let overlapLo = overlapFit;
    let overlapHi = Math.min(overlapProbe, pieceLength - 1);

    while (overlapLo < overlapHi) {
      const mid = overlapLo + Math.ceil((overlapHi - overlapLo) / 2);
      if (
        countTokens(chars.slice(pieceEnd - mid, pieceEnd).join('')) <=
        overlapTokens
      ) {
        overlapLo = mid;
      } else {
        overlapHi = mid - 1;
      }
    }

    start = pieceEnd - overlapLo;
  }

  return pieces;
}

// Returns the trailing text of `text` that fits within `overlapTokens`,
// breaking only on whitespace so it never cuts a word in half — oversized
// single "words" are already handled separately by splitOversizedWord.
function getOverlapTail(text: string, overlapTokens: number): string {
  if (overlapTokens <= 0 || !text) {
    return '';
  }

  const words = text.split(/\s+/).filter(Boolean);
  let tail: string[] = [];

  for (let i = words.length - 1; i >= 0; i--) {
    const candidate = [words[i], ...tail];
    if (countTokens(candidate.join(' ')) > overlapTokens) {
      break;
    }
    tail = candidate;
  }

  return tail.join(' ');
}

function addChunk(
  chunks: JournalDocument[],
  document: JournalDocument,
  content: string,
): void {
  if (!content.trim()) {
    return;
  }

  chunks.push({
    ...document,
    content: content.trim(),
  });
}

// The effective split budget after QWEN_SAFETY_MARGIN — the real limit every
// fit-check in chunkDocument enforces, and what overlapTokens is validated
// and defaulted against, since overlapTokens must leave room under the
// budget that's actually applied, not the resolved maxTokens (whether from
// an explicit argument, SOURCE_TYPE_CHUNK_CONFIG, or the scaled default).
function getEffectiveMaxTokens(maxTokens: number): number {
  return Math.max(1, Math.floor(maxTokens * QWEN_SAFETY_MARGIN));
}

// Resolves the maxTokens/overlapTokens to use for a document: an explicit
// argument wins, then the sourceType's entry in `config`, then undefined
// (chunkDocument applies its own scaled default for overlapTokens). Takes
// `config` as a parameter — rather than reading SOURCE_TYPE_CHUNK_CONFIG
// directly — purely so tests can exercise per-sourceType differentiation
// with a local literal config, without mutating the shared, Readonly export.
export function resolveChunkBudget(
  sourceType: DocumentSourceType,
  maxTokens: number | undefined,
  overlapTokens: number | undefined,
  config: Readonly<
    Record<DocumentSourceType, Readonly<{ maxTokens: number; overlapTokens?: number }>>
  > = SOURCE_TYPE_CHUNK_CONFIG,
): { maxTokens: number; overlapTokens?: number } {
  const sourceConfig = config[sourceType];
  return {
    maxTokens: maxTokens ?? sourceConfig.maxTokens,
    overlapTokens: overlapTokens ?? sourceConfig.overlapTokens,
  };
}

// Splits `text` into sentences and, for any sentence that doesn't fit,
// further into words (and, for oversized words, hard-split pieces),
// pushing full chunks to `chunks` as it goes. `seed` is the overlap text
// carried in from whatever fit level called this (paragraph, field, or the
// top level). Returns the trailing, not-yet-pushed remainder so the caller
// can keep accumulating across further paragraphs/fields.
function processSentences(
  chunks: JournalDocument[],
  document: JournalDocument,
  text: string,
  seed: string,
  effectiveMaxTokens: number,
  overlapTokens: number,
): string {
  let currentChunk = seed;
  const sentences = splitIntoSentences(text);

  for (const sentence of sentences) {
    const sentenceCandidate = currentChunk
      ? `${currentChunk} ${sentence}`
      : sentence;

    if (countTokens(sentenceCandidate) <= effectiveMaxTokens) {
      currentChunk = sentenceCandidate;
      continue;
    }

    // Sentence candidate doesn't fit, so save it and keep its trailing
    // text as overlap seed for whatever comes next.
    let sentenceOverlapSeed = '';
    if (currentChunk) {
      addChunk(chunks, document, currentChunk);
      sentenceOverlapSeed = getOverlapTail(currentChunk, overlapTokens);
    }

    // Now we're starting with the sentence alone.
    if (countTokens(sentence) <= effectiveMaxTokens) {
      const seeded = sentenceOverlapSeed
        ? `${sentenceOverlapSeed} ${sentence}`
        : sentence;
      currentChunk =
        countTokens(seeded) <= effectiveMaxTokens ? seeded : sentence;
      continue;
    }

    // The sentence itself is too large. Carry the overlap seed forward as
    // the starting point for the first word.
    const words = sentence.split(/\s+/);
    let sentenceChunk = sentenceOverlapSeed;

    for (const word of words) {
      const candidate = sentenceChunk ? `${sentenceChunk} ${word}` : word;

      if (countTokens(candidate) <= effectiveMaxTokens) {
        sentenceChunk = candidate;
      } else if (countTokens(word) > effectiveMaxTokens) {
        let wordOverlapSeed = '';
        if (sentenceChunk) {
          addChunk(chunks, document, sentenceChunk);
          wordOverlapSeed = getOverlapTail(sentenceChunk, overlapTokens);
        }

        const pieces = splitOversizedWord(
          wordOverlapSeed ? `${wordOverlapSeed} ${word}` : word,
          effectiveMaxTokens,
          overlapTokens,
        );
        for (const piece of pieces.slice(0, -1)) {
          addChunk(chunks, document, piece);
        }

        sentenceChunk = pieces[pieces.length - 1] ?? '';
      } else {
        let wordOverlapSeed = '';
        if (sentenceChunk) {
          addChunk(chunks, document, sentenceChunk);
          wordOverlapSeed = getOverlapTail(sentenceChunk, overlapTokens);
        }

        const seeded = wordOverlapSeed
          ? `${wordOverlapSeed} ${word}`
          : word;
        sentenceChunk =
          countTokens(seeded) <= effectiveMaxTokens ? seeded : word;
      }
    }

    if (sentenceChunk) {
      currentChunk = sentenceChunk;
    }
  }

  return currentChunk;
}

// Splits `text` into labeled fields (see splitIntoFields) and, for any
// field that doesn't fit, falls through to sentence-level splitting. When
// no field boundary exists (the common case for terse records with a
// single label), defers straight to processSentences — identical to the
// pre-field-splitting behavior. Mirrors the paragraph-level fit/seed
// pattern in chunkDocument one level down.
function processFields(
  chunks: JournalDocument[],
  document: JournalDocument,
  text: string,
  seed: string,
  effectiveMaxTokens: number,
  overlapTokens: number,
): string {
  const fields = splitIntoFields(text);

  if (fields.length <= 1) {
    return processSentences(
      chunks,
      document,
      text,
      seed,
      effectiveMaxTokens,
      overlapTokens,
    );
  }

  let currentChunk = seed;

  for (const field of fields) {
    const fieldCandidate = currentChunk ? `${currentChunk} ${field}` : field;

    if (countTokens(fieldCandidate) <= effectiveMaxTokens) {
      currentChunk = fieldCandidate;
      continue;
    }

    let fieldOverlapSeed = '';
    if (currentChunk) {
      addChunk(chunks, document, currentChunk);
      fieldOverlapSeed = getOverlapTail(currentChunk, overlapTokens);
    }

    if (countTokens(field) <= effectiveMaxTokens) {
      const seeded = fieldOverlapSeed
        ? `${fieldOverlapSeed} ${field}`
        : field;
      currentChunk =
        countTokens(seeded) <= effectiveMaxTokens ? seeded : field;
      continue;
    }

    currentChunk = processSentences(
      chunks,
      document,
      field,
      fieldOverlapSeed,
      effectiveMaxTokens,
      overlapTokens,
    );
  }

  return currentChunk;
}

export function chunkDocument(
  document: JournalDocument,
  maxTokens?: number,
  overlapTokens?: number,
): JournalDocument[] {
  const resolvedBudget = resolveChunkBudget(
    document.metadata.sourceType,
    maxTokens,
    overlapTokens,
  );
  const resolvedMaxTokens = resolvedBudget.maxTokens;

  if (!(resolvedMaxTokens >= 1)) {
    throw new Error(
      `maxTokens must be at least 1, received ${resolvedMaxTokens}`,
    );
  }

  // Split against a reduced budget (see QWEN_SAFETY_MARGIN) so a chunk that
  // measures at maxTokens under cl100k_base still stays under maxTokens real
  // Qwen3 tokens.
  const effectiveMaxTokens = getEffectiveMaxTokens(resolvedMaxTokens);

  const resolvedOverlapTokens =
    resolvedBudget.overlapTokens ??
    Math.min(DEFAULT_OVERLAP_TOKENS, Math.floor(effectiveMaxTokens / 4));

  if (!(resolvedOverlapTokens >= 0)) {
    throw new Error(
      `overlapTokens must be at least 0, received ${resolvedOverlapTokens}`,
    );
  }

  if (resolvedOverlapTokens >= effectiveMaxTokens) {
    throw new Error(
      `overlapTokens (${resolvedOverlapTokens}) must be less than the ` +
        `effective token budget (${effectiveMaxTokens}, derived from ` +
        `maxTokens ${resolvedMaxTokens})`,
    );
  }

  if (!document.content.trim()) {
    return [];
  }

  // Keep small journal records intact.
  if (countTokens(document.content) <= effectiveMaxTokens) {
    return [document];
  }

  const paragraphs = splitIntoParagraphs(document.content);

  const chunks: JournalDocument[] = [];
  let currentChunk = '';

  for (const paragraph of paragraphs) {
    const paragraphCandidate = currentChunk
      ? `${currentChunk}\n\n${paragraph}`
      : paragraph;

    // The paragraph fits in the current chunk.
    if (countTokens(paragraphCandidate) <= effectiveMaxTokens) {
      currentChunk = paragraphCandidate;
      continue;
    }

    // Save the current chunk before processing the large paragraph, keeping
    // its trailing text as overlap seed for whatever comes next.
    let paragraphOverlapSeed = '';
    if (currentChunk) {
      addChunk(chunks, document, currentChunk);
      paragraphOverlapSeed = getOverlapTail(
        currentChunk,
        resolvedOverlapTokens,
      );
    }

    // The paragraph itself fits in one chunk.
    if (countTokens(paragraph) <= effectiveMaxTokens) {
      const seeded = paragraphOverlapSeed
        ? `${paragraphOverlapSeed}\n\n${paragraph}`
        : paragraph;
      currentChunk =
        countTokens(seeded) <= effectiveMaxTokens ? seeded : paragraph;
      continue;
    }

    // The paragraph is too large, so try splitting it on labeled-field
    // boundaries (falls straight through to sentence-splitting when the
    // paragraph has no such boundary). Carry the overlap seed forward as
    // the starting point for the first field/sentence.
    currentChunk = processFields(
      chunks,
      document,
      paragraph,
      paragraphOverlapSeed,
      effectiveMaxTokens,
      resolvedOverlapTokens,
    );
  }

  // Save the final chunk.
  if (currentChunk) {
    addChunk(chunks, document, currentChunk);
  }

  return chunks;
}

export function chunkDocuments(
  documents: JournalDocument[],
  maxTokens?: number,
  overlapTokens?: number,
): JournalDocument[] {
  return documents.flatMap((document) =>
    chunkDocument(document, maxTokens, overlapTokens),
  );
}
